//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeonardCRM.DataLayer.ModelEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Eli_ViewColumns
    {
        public int Id { get; set; }
        public int ViewId { get; set; }
        public int FieldId { get; set; }
        public int SortOrder { get; set; }
        public string Width { get; set; }
        public bool Visible { get; set; }
        public Nullable<bool> IsCommand { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
    
        public virtual Eli_Views Eli_Views { get; set; }
    }
}
