//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeonardCRM.DataLayer.ModelEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Eli_Views
    {
        public Eli_Views()
        {
            this.Eli_ViewColumns = new HashSet<Eli_ViewColumns>();
            this.Eli_ViewConditions = new HashSet<Eli_ViewConditions>();
            this.Eli_ViewGroupBy = new HashSet<Eli_ViewGroupBy>();
            this.Eli_ViewOrderBy = new HashSet<Eli_ViewOrderBy>();
        }
    
        public int Id { get; set; }
        public string ViewName { get; set; }
        public bool IsPublic { get; set; }
        public bool Shared { get; set; }
        public int SortOrder { get; set; }
        public int ModuleId { get; set; }
        public string QueryScript { get; set; }
        public string ParentId { get; set; }
        public bool LoadChildView { get; set; }
        public bool DefaultView { get; set; }
        public Nullable<int> PageSize { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> MasterViewId { get; set; }
        public string UserRole { get; set; }
        public Nullable<bool> IsCollapsed { get; set; }
        public string CollapseStatus { get; set; }
    
        public virtual Eli_Modules Eli_Modules { get; set; }
        public virtual ICollection<Eli_ViewColumns> Eli_ViewColumns { get; set; }
        public virtual ICollection<Eli_ViewConditions> Eli_ViewConditions { get; set; }
        public virtual ICollection<Eli_ViewGroupBy> Eli_ViewGroupBy { get; set; }
        public virtual ICollection<Eli_ViewOrderBy> Eli_ViewOrderBy { get; set; }
    }
}
