//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeonardCRM.DataLayer.ModelEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Eli_ListDependency
    {
        public Eli_ListDependency()
        {
            this.Eli_ListDependencyDetail = new HashSet<Eli_ListDependencyDetail>();
        }
    
        public int Id { get; set; }
        public int ModuleId { get; set; }
        public int MasterFieldId { get; set; }
        public int ChildFieldId { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual ICollection<Eli_ListDependencyDetail> Eli_ListDependencyDetail { get; set; }
    }
}
