//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeonardCRM.DataLayer.ModelEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Eli_SysAudit
    {
        public long Id { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public int ModuleId { get; set; }
        public int MasterRecordId { get; set; }
        public string Operation { get; set; }
        public string ColumnName { get; set; }
        public string ValueBefore { get; set; }
        public string ValueAfter { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
    
        public virtual Eli_User Eli_User { get; set; }
    }
}
