//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeonardCRM.DataLayer.ModelEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Eli_DataTypes
    {
        public Eli_DataTypes()
        {
            this.Eli_EntityFields = new HashSet<Eli_EntityFields>();
        }
    
        public int Id { get; set; }
        public string TypeName { get; set; }
        public bool IsInteger { get; set; }
        public bool IsDate { get; set; }
        public bool IsDateTime { get; set; }
        public bool IsDecimal { get; set; }
        public bool IsCurrency { get; set; }
        public bool IsText { get; set; }
        public bool IsList { get; set; }
        public bool IsTextArea { get; set; }
        public bool IsTime { get; set; }
        public bool IsEmail { get; set; }
        public bool IsUrl { get; set; }
        public bool IsMultiSelecttBox { get; set; }
        public bool IsCheckBox { get; set; }
        public bool IsImage { get; set; }
        public bool IsPublic { get; set; }
    
        public virtual ICollection<Eli_EntityFields> Eli_EntityFields { get; set; }
    }
}
