//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeonardCRM.DataLayer.ModelEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Eli_User
    {
        public Eli_User()
        {
            this.Eli_SysAudit = new HashSet<Eli_SysAudit>();
            this.Eli_ViewCustom = new HashSet<Eli_ViewCustom>();
            this.SalesCustomerUsers = new HashSet<SalesCustomerUser>();
            this.SalesOrdersUsers = new HashSet<SalesOrdersUser>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string LoginName { get; set; }
        public string Password { get; set; }
        public string Phone { get; set; }
        public int Status { get; set; }
        public Nullable<System.Guid> ActivationCode { get; set; }
        public string Avatar { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public int RoleId { get; set; }
        public Nullable<System.DateTime> LastLogin { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> StoreId { get; set; }
        public string Signature { get; set; }
    
        public virtual Eli_Roles Eli_Roles { get; set; }
        public virtual ICollection<Eli_SysAudit> Eli_SysAudit { get; set; }
        public virtual ICollection<Eli_ViewCustom> Eli_ViewCustom { get; set; }
        public virtual ICollection<SalesCustomerUser> SalesCustomerUsers { get; set; }
        public virtual ICollection<SalesOrdersUser> SalesOrdersUsers { get; set; }
    }
}
