//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeonardCRM.DataLayer.ModelEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Eli_ViewCustomConditions
    {
        public int Id { get; set; }
        public int ViewId { get; set; }
        public string ColumnName { get; set; }
        public int FieldId { get; set; }
        public string Operator { get; set; }
        public string FilterValue { get; set; }
        public string FilterValue1 { get; set; }
        public bool IsAND { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
    
        public virtual Eli_ViewCustom Eli_ViewCustom { get; set; }
    }
}
