//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeonardCRM.DataLayer.ModelEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Eli_TempViews
    {
        public int Id { get; set; }
        public string ViewName { get; set; }
        public bool IsPublic { get; set; }
        public bool Shared { get; set; }
        public int SortOrder { get; set; }
        public int ModuleId { get; set; }
        public string QueryScript { get; set; }
        public string ParentId { get; set; }
        public bool LoadChildView { get; set; }
        public bool DefaultView { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public bool IsActive { get; set; }
        public int ViewParentId { get; set; }
        public Nullable<bool> IsCollapsed { get; set; }
        public string CollapseStatus { get; set; }
    }
}
