//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeonardCRM.DataLayer.ModelEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Eli_Modules
    {
        public Eli_Modules()
        {
            this.Eli_EntityFields = new HashSet<Eli_EntityFields>();
            this.Eli_RolesPermissions = new HashSet<Eli_RolesPermissions>();
            this.Eli_Views = new HashSet<Eli_Views>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string DisplayName { get; set; }
        public string FeatureName { get; set; }
        public string Description { get; set; }
        public bool Dashboard { get; set; }
        public string DefaultTable { get; set; }
        public string IconClass { get; set; }
        public string MenuIcon { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> SortOrder { get; set; }
        public int Parent { get; set; }
        public bool IsPublished { get; set; }
        public Nullable<int> RelatedTo { get; set; }
        public bool NeedPickList { get; set; }
        public bool ReportModule { get; set; }
        public bool AllowCreateView { get; set; }
        public bool AllowImport { get; set; }
        public bool AllowExport { get; set; }
        public bool IsWebform { get; set; }
    
        public virtual ICollection<Eli_EntityFields> Eli_EntityFields { get; set; }
        public virtual ICollection<Eli_RolesPermissions> Eli_RolesPermissions { get; set; }
        public virtual ICollection<Eli_Views> Eli_Views { get; set; }
    }
}
