//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeonardCRM.DataLayer.ModelEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Eli_Roles
    {
        public Eli_Roles()
        {
            this.Eli_RolesFields = new HashSet<Eli_RolesFields>();
            this.Eli_RolesPermissions = new HashSet<Eli_RolesPermissions>();
            this.Eli_User = new HashSet<Eli_User>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Parent { get; set; }
        public bool IsHostAdmin { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual ICollection<Eli_RolesFields> Eli_RolesFields { get; set; }
        public virtual ICollection<Eli_RolesPermissions> Eli_RolesPermissions { get; set; }
        public virtual ICollection<Eli_User> Eli_User { get; set; }
    }
}
