//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeonardCRM.DataLayer.ModelEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Eli_ViewCustomColumns
    {
        public int Id { get; set; }
        public int ViewCustomId { get; set; }
        public int FieldId { get; set; }
        public int SortOrder { get; set; }
        public bool Visible { get; set; }
        public string DefaultWidth { get; set; }
        public string ColumnAlias { get; set; }
        public string TableAlias { get; set; }
        public Nullable<bool> IsDefault { get; set; }
        public Nullable<int> DataType { get; set; }
        public string DisplayText { get; set; }
    
        public virtual Eli_EntityFields Eli_EntityFields { get; set; }
        public virtual Eli_ViewCustom Eli_ViewCustom { get; set; }
    }
}
