//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeonardCRM.DataLayer.ModelEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesContractState
    {
        public int Id { get; set; }
        public int ContractId { get; set; }
        public int StateId { get; set; }
    
        public virtual SalesContractTemplate SalesContractTemplate { get; set; }
    }
}
