//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeonardCRM.DataLayer.ModelEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesOrderComplete
    {
        public int Id { get; set; }
        public int OrderId { get; set; }
        public System.DateTime DeliveryDate { get; set; }
        public Nullable<bool> NeedRepair { get; set; }
        public string RepairNote { get; set; }
        public Nullable<bool> Answer1 { get; set; }
        public Nullable<bool> Answer2 { get; set; }
        public Nullable<bool> Answer3 { get; set; }
        public Nullable<bool> Answer4 { get; set; }
        public Nullable<bool> Answer5 { get; set; }
        public string DeliveryType { get; set; }
        public string DeliveryOther { get; set; }
        public Nullable<int> ActBlocksUsed { get; set; }
        public Nullable<decimal> ActHoursOfLabor { get; set; }
        public Nullable<decimal> ActMilesToSite { get; set; }
        public Nullable<decimal> BalanceDue { get; set; }
        public bool AdditionalCharge { get; set; }
        public Nullable<int> PaymentType { get; set; }
        public Nullable<decimal> BlockCharge { get; set; }
        public Nullable<decimal> LaborCharge { get; set; }
        public Nullable<decimal> MileageCharge { get; set; }
        public Nullable<decimal> TotalAmountDue { get; set; }
        public Nullable<bool> WarrantyReceived { get; set; }
        public Nullable<bool> Satisfy { get; set; }
        public string NoSatisfyComment { get; set; }
        public Nullable<int> Rating { get; set; }
        public string Signature { get; set; }
        public Nullable<System.DateTime> SignDate { get; set; }
        public string SignIP { get; set; }
        public Nullable<bool> FollowUpCall { get; set; }
        public Nullable<System.DateTime> CallDate { get; set; }
        public Nullable<bool> SpokeWithCustomer { get; set; }
        public string FollowUpComment { get; set; }
        public string ManagerSignature { get; set; }
        public Nullable<System.DateTime> ManagerSignDate { get; set; }
        public string ManagerSignIP { get; set; }
        public string DeliverSignature { get; set; }
        public Nullable<System.DateTime> DeliverSignDate { get; set; }
        public string DeliverSignIP { get; set; }
        public string DeliveryPersonInitials { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public bool IsActive { get; set; }
        public Nullable<bool> LeftVoiceMail { get; set; }
    
        public virtual SalesOrder SalesOrder { get; set; }
    }
}
