//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeonardCRM.DataLayer.ModelEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesCustomer
    {
        public SalesCustomer()
        {
            this.SalesCustReferences = new HashSet<SalesCustReference>();
            this.SalesCustomerUsers = new HashSet<SalesCustomerUser>();
            this.SalesOrders = new HashSet<SalesOrder>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public Nullable<int> SocialNum { get; set; }
        public string DriverLicense { get; set; }
        public string HomePhone { get; set; }
        public string CellPhone { get; set; }
        public string Email { get; set; }
        public string PhysicalStreet { get; set; }
        public string PhysicalCity { get; set; }
        public Nullable<int> PhysicalState { get; set; }
        public string PhysicalZip { get; set; }
        public string MailingStreet { get; set; }
        public string MailingCity { get; set; }
        public Nullable<int> MailingState { get; set; }
        public string MailingZip { get; set; }
        public Nullable<System.DateTime> AtAddressSince { get; set; }
        public Nullable<int> ResidenceType { get; set; }
        public Nullable<int> LandType { get; set; }
        public string LandlordName { get; set; }
        public string LandlordPhone { get; set; }
        public Nullable<bool> CheckingAccount { get; set; }
        public Nullable<bool> SavingAccount { get; set; }
        public Nullable<bool> EnrollAutoPay { get; set; }
        public string CoName { get; set; }
        public Nullable<System.DateTime> CoDateOfBirth { get; set; }
        public Nullable<int> CoSocialNum { get; set; }
        public string CoDriverLicense { get; set; }
        public string CoCellPhone { get; set; }
        public string CoEmail { get; set; }
        public string Employer { get; set; }
        public Nullable<System.DateTime> Since { get; set; }
        public string Phone { get; set; }
        public string Supervisor { get; set; }
        public string CoEmployer { get; set; }
        public Nullable<System.DateTime> CoSince { get; set; }
        public string CoPhone { get; set; }
        public string CoSupervisor { get; set; }
        public string TypeOfBusiness { get; set; }
        public Nullable<System.DateTime> BusinessSince { get; set; }
        public string ResponsibleUsers { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public bool IsActive { get; set; }
        public Nullable<bool> SelfEmployed { get; set; }
        public string IncomeExplanation { get; set; }
        public string CustomerInitials { get; set; }
        public Nullable<bool> IsSameMailingAddress { get; set; }
    
        public virtual ICollection<SalesCustReference> SalesCustReferences { get; set; }
        public virtual ICollection<SalesCustomerUser> SalesCustomerUsers { get; set; }
        public virtual ICollection<SalesOrder> SalesOrders { get; set; }
    }
}
