//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeonardCRM.DataLayer.ModelEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesOrder
    {
        public SalesOrder()
        {
            this.SalesDocuments = new HashSet<SalesDocument>();
            this.SalesInvoices = new HashSet<SalesInvoice>();
            this.SalesOrderCompletes = new HashSet<SalesOrderComplete>();
            this.SalesOrderDeliveries = new HashSet<SalesOrderDelivery>();
            this.SalesOrdersUsers = new HashSet<SalesOrdersUser>();
        }
    
        public int Id { get; set; }
        public int Status { get; set; }
        public int CustomerId { get; set; }
        public string GPCustomerID { get; set; }
        public Nullable<System.DateTime> AcceptDate { get; set; }
        public string PromoCode { get; set; }
        public string GPOrderNumber { get; set; }
        public Nullable<int> StoreNumber { get; set; }
        public Nullable<bool> IsOldCustomer { get; set; }
        public string PartNumber { get; set; }
        public string SerialNumber { get; set; }
        public string Color { get; set; }
        public Nullable<decimal> SalesPrice { get; set; }
        public Nullable<bool> IsNewPart { get; set; }
        public Nullable<decimal> MonthlyPayment1 { get; set; }
        public Nullable<decimal> MonthlyPayment2 { get; set; }
        public Nullable<decimal> PaidAtSigning { get; set; }
        public Nullable<decimal> RampPaidAtSign { get; set; }
        public Nullable<decimal> ReductionPayment { get; set; }
        public Nullable<decimal> RampReduction { get; set; }
        public Nullable<decimal> Tax { get; set; }
        public Nullable<decimal> RampTax { get; set; }
        public Nullable<decimal> TotalMonthly { get; set; }
        public string RampPartNumber { get; set; }
        public Nullable<int> CapitalizationPeriod { get; set; }
        public string LesseeSignature { get; set; }
        public Nullable<System.DateTime> SignatureDate { get; set; }
        public string SignatureIP { get; set; }
        public string CoSignature { get; set; }
        public Nullable<System.DateTime> CoSignatureDate { get; set; }
        public string CoSignatureIP { get; set; }
        public string ResponsibleUsers { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public bool IsActive { get; set; }
        public string POSTicketNumber { get; set; }
        public Nullable<bool> RentToOwn { get; set; }
        public Nullable<System.DateTime> SaleDate { get; set; }
        public Nullable<bool> IsFinalize { get; set; }
        public Nullable<int> TotalPoint { get; set; }
        public Nullable<decimal> SaleTax { get; set; }
        public int NumberOfPayment { get; set; }
        public Nullable<bool> IsAddPromotion { get; set; }
        public Nullable<decimal> PromotionAmt { get; set; }
        public string DisapprovedReason { get; set; }
        public Nullable<bool> IsApproveOrder { get; set; }
        public Nullable<decimal> SalesTaxPercent { get; set; }
        public Nullable<decimal> RampSalePrice { get; set; }
        public bool DriverAssigned { get; set; }
        public Nullable<bool> IsSold { get; set; }
    
        public virtual SalesCustomer SalesCustomer { get; set; }
        public virtual ICollection<SalesDocument> SalesDocuments { get; set; }
        public virtual ICollection<SalesInvoice> SalesInvoices { get; set; }
        public virtual ICollection<SalesOrderComplete> SalesOrderCompletes { get; set; }
        public virtual ICollection<SalesOrderDelivery> SalesOrderDeliveries { get; set; }
        public virtual ICollection<SalesOrdersUser> SalesOrdersUsers { get; set; }
    }
}
