//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeonardCRM.DataLayer.ModelEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwClient
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> ResponsibleUser { get; set; }
        public int RoleId { get; set; }
    }
}
