//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeonardCRM.DataLayer.ModelEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwCustomViewColumn
    {
        public int Id { get; set; }
        public int ViewCustomId { get; set; }
        public string ColumnName { get; set; }
        public int SortOrder { get; set; }
        public string LabelDisplay { get; set; }
        public bool IsInteger { get; set; }
        public bool IsDate { get; set; }
        public bool IsDecimal { get; set; }
        public bool IsText { get; set; }
        public bool IsList { get; set; }
        public bool IsTextArea { get; set; }
        public bool IsTime { get; set; }
        public bool IsEmail { get; set; }
        public bool IsUrl { get; set; }
        public bool IsMultiSelecttBox { get; set; }
        public bool IsCheckBox { get; set; }
        public bool IsImage { get; set; }
        public bool Display { get; set; }
        public Nullable<bool> Sortable { get; set; }
        public Nullable<bool> Searchable { get; set; }
        public bool Mandatory { get; set; }
        public bool IsDateTime { get; set; }
        public bool IsCurrency { get; set; }
        public Nullable<bool> AllowGroup { get; set; }
        public bool Visible { get; set; }
        public int FieldId { get; set; }
        public Nullable<bool> Deletable { get; set; }
        public string ColumnAlias { get; set; }
        public string TableAlias { get; set; }
        public Nullable<bool> IsDefault { get; set; }
        public Nullable<bool> ForeignKey { get; set; }
        public Nullable<int> DataType { get; set; }
        public string TypeName { get; set; }
        public string DisplayText { get; set; }
        public string DefaultWidth { get; set; }
    }
}
