//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeonardCRM.DataLayer.ModelEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwFieldsDataType
    {
        public string FieldName { get; set; }
        public bool IsInteger { get; set; }
        public bool IsDate { get; set; }
        public bool IsDecimal { get; set; }
        public bool IsText { get; set; }
        public bool IsList { get; set; }
        public bool IsTextArea { get; set; }
        public bool IsTime { get; set; }
        public bool IsEmail { get; set; }
        public bool IsUrl { get; set; }
        public bool IsMultiSelecttBox { get; set; }
        public bool IsCheckBox { get; set; }
        public int DataTypeId { get; set; }
        public int ModuleId { get; set; }
        public Nullable<int> DataLength { get; set; }
        public bool Mandatory { get; set; }
        public string LabelDisplay { get; set; }
        public bool IsUnique { get; set; }
        public bool PrimaryKey { get; set; }
        public bool IsDateTime { get; set; }
        public int FieldId { get; set; }
        public Nullable<bool> Deletable { get; set; }
        public bool IsCurrency { get; set; }
        public bool ForeignKey { get; set; }
        public bool Display { get; set; }
        public string RegularExpression { get; set; }
        public Nullable<bool> IsTextShow { get; set; }
        public Nullable<int> Point { get; set; }
    }
}
