//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeonardCRM.DataLayer.ModelEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwFieldNameDataType
    {
        public int Id { get; set; }
        public int ViewId { get; set; }
        public string ColumnName { get; set; }
        public bool IsCommand { get; set; }
        public int SortOrder { get; set; }
        public string LabelDisplay { get; set; }
        public int ModuleId { get; set; }
        public string TypeName { get; set; }
        public bool IsInteger { get; set; }
        public bool IsDate { get; set; }
        public bool IsDecimal { get; set; }
        public bool IsText { get; set; }
        public bool IsList { get; set; }
        public bool IsTextArea { get; set; }
        public bool IsTime { get; set; }
        public bool IsEmail { get; set; }
        public bool IsUrl { get; set; }
        public bool IsMultiSelecttBox { get; set; }
        public bool IsCheckBox { get; set; }
        public string Name { get; set; }
        public bool LoadChildView { get; set; }
        public string DefaultTable { get; set; }
        public bool IsImage { get; set; }
        public bool Display { get; set; }
        public Nullable<bool> Sortable { get; set; }
        public Nullable<bool> Searchable { get; set; }
        public bool Mandatory { get; set; }
        public bool IsDateTime { get; set; }
        public bool IsCurrency { get; set; }
        public Nullable<bool> AllowGroup { get; set; }
        public string Width { get; set; }
        public bool Visible { get; set; }
        public int FieldId { get; set; }
        public bool Locked { get; set; }
        public Nullable<bool> Show { get; set; }
        public int RoleId { get; set; }
        public Nullable<bool> Deletable { get; set; }
        public Nullable<bool> IsTextShow { get; set; }
    }
}
