//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeonardCRM.DataLayer.ModelEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwField
    {
        public int FieldId { get; set; }
        public string ColumnName { get; set; }
        public int ModuleId { get; set; }
        public int SortOrder { get; set; }
        public bool IsDate { get; set; }
        public bool IsList { get; set; }
        public bool IsMultiSelecttBox { get; set; }
        public bool IsCheckBox { get; set; }
        public string LabelDisplay { get; set; }
        public Nullable<bool> AdvanceSearch { get; set; }
        public bool Display { get; set; }
        public bool IsDateTime { get; set; }
        public bool IsDecimal { get; set; }
        public bool IsInteger { get; set; }
        public Nullable<bool> Sortable { get; set; }
        public bool IsCurrency { get; set; }
        public Nullable<bool> AllowGroup { get; set; }
    }
}
