//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeonardCRM.DataLayer.ModelEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwListNameValue
    {
        public string FieldName { get; set; }
        public int ModuleId { get; set; }
        public Nullable<int> ListNameId { get; set; }
        public int LookupId { get; set; }
        public string Description { get; set; }
        public int Id { get; set; }
        public bool Active { get; set; }
        public string AdditionalInfo { get; set; }
        public int ListOrder { get; set; }
    }
}
