//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeonardCRM.DataLayer.ModelEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwModuleEntityField
    {
        public int Id { get; set; }
        public string FieldName { get; set; }
        public Nullable<bool> ForeignKey { get; set; }
        public bool IsList { get; set; }
        public int ModuleId { get; set; }
        public string Name { get; set; }
        public string DefaultTable { get; set; }
        public bool IsCheckBox { get; set; }
        public bool IsDecimal { get; set; }
        public bool IsInteger { get; set; }
        public bool IsDate { get; set; }
        public bool IsDateTime { get; set; }
        public bool IsCurrency { get; set; }
        public bool Mandatory { get; set; }
        public Nullable<bool> Deletable { get; set; }
        public bool IsMultiSelecttBox { get; set; }
        public bool Display { get; set; }
        public Nullable<bool> IsTextShow { get; set; }
    }
}
