//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeonardCRM.DataLayer.ModelEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwModuleEnittyRelationship
    {
        public int Id { get; set; }
        public int MasterId { get; set; }
        public string MasterFieldName { get; set; }
        public Nullable<bool> MasterForeignKey { get; set; }
        public int MasterModuleId { get; set; }
        public string MasterDefaultTable { get; set; }
        public string MasterDisplayColumn { get; set; }
        public string MasterAlias { get; set; }
        public int ChildId { get; set; }
        public string ChildFieldName { get; set; }
        public Nullable<bool> ChildForeignKey { get; set; }
        public int ChildModuleId { get; set; }
        public string ChildDefaultTable { get; set; }
        public string ChildDisplayColumn { get; set; }
        public string LabelDisplay { get; set; }
        public string MasterModule { get; set; }
        public string ChildModule { get; set; }
        public int DataTypeId { get; set; }
    }
}
