//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeonardCRM.DataLayer.ModelEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwPicklistDependency
    {
        public int ModuleId { get; set; }
        public int MasterFieldId { get; set; }
        public int ChildFieldId { get; set; }
        public int MasterValueId { get; set; }
        public int ChildValueId { get; set; }
    }
}
